### PR TITLE
Added responsive navbar

### PR DESCRIPTION
**Pull request by Mayor-Rhymes**
@ArinzeJeffrey-droid. I made some changes to the navigation bar and I also made sure that they were formatted properly. I feel there are better ways to do it. Your input will be greatly appreciated. Also, working this way is so nice. I am getting so much done and it feels like my account is busier.

### CODE REVIEW

**Comment by ArinzeJeffrey-droid** [comment]
@Mayor-Rhymes Does the mobile navbar pushes down the content when opened? If yes, why not make it overlap the content, because the sudden jump in the UI might trigger users, WDYT?

**Comment by ArinzeJeffrey-droid** [comment]
Also if you have time tonight we could take a look at how to integrate github workflows in your project

**Comment by Mayor-Rhymes** [comment]
> @Mayor-Rhymes Does the mobile navbar pushes down the content when opened? If yes, why not make it overlap the content, because the sudden jump in the UI might trigger users, WDYT?

Oh Ok. I will do something about that.

**Comment by Mayor-Rhymes** [comment]
@ArinzeJeffrey-droid Is this okay?

**Review by ArinzeJeffrey-droid — APPROVED** [review]

**Pull request merged**
