### PR TITLE
Feat: Added Calculator page and also designed simple calculator

### PR DESCRIPTION
**Pull request by Mayor-Rhymes**
Hello @ArinzeJeffrey-droid, what do you think about the calculator design?

### CODE REVIEW

**Comment by ArinzeJeffrey-droid** [comment]
@Mayor-Rhymes It helps to provide screenshots of the UI 😃

**Comment by Mayor-Rhymes** [comment]
Here is a screenshot

calculator

**Comment by Mayor-Rhymes** [comment]
Also, here is a video of the button transition from pressed to "unpressed".  Not much but I like the subtle feeling of pressing a physical button. I hope it looks good?
https://github.com/Mayor-Rhymes/utility-web/assets/35629340/a7cb6151-8d55-42ed-b605-59d765870e51

**Comment by ArinzeJeffrey-droid** [comment]
Looks great! @Mayor-Rhymes 
One thing though, you shouldn't put the video demo inside of your repo.
You can always attach the video or image of what ever UI you built in the PR description.
You can use a screen recording tool on your laptop and record a short demo of the UI, and sometimes you might have to just record just the aspect of the UI you want to demo so as not to use the full resolution of your laptop screen because of the file size limit constraint when adding files to the PR description.

I hope it makes sense? If not, let me know where is not clear. :)

**Comment by Mayor-Rhymes** [comment]
I understand you. 
Weirdly enough, I attached the video file to the conversation. I am also surprised it is being stored in an assets folder.
Any explanation as to why it does that?
Also, the video has been compressed to about 7mb.

**Comment by ArinzeJeffrey-droid** [comment]
@Mayor-Rhymes OOOH I see, it's just github way of storing the files using AWS s3 bucket, Ignore my comment.
🙏🏾

**Comment by Mayor-Rhymes** [comment]
problem
@ArinzeJeffrey-droid, I don't quite understand what is happening here. Can you explain it to me like I am 5? Thanks.

**Comment by ArinzeJeffrey-droid** [comment]
You mean the "Merging is block" warning? @Mayor-Rhymes 
If yes, it has to do with a security settings on your repo to not merge a pull request without an approval.
Which means if I click the approve button on my end the warning should disappear. I think.

**Review by ArinzeJeffrey-droid — APPROVED** [review]

**Comment by Mayor-Rhymes** [comment]
Oh yes. The warning has disappeared. So, I can merge to this branch to main now, right?

**Comment by ArinzeJeffrey-droid** [comment]
@Mayor-Rhymes Yes you can 🚀 
LGTM

(LGTM) Looks Good To Merge. It's lingo we use sometimes on PRs 😄

**Comment by Mayor-Rhymes** [comment]
Also, I like that feature. Nice to know that if a PR has not been approved, it is not going to be merged. Very nice.

**Comment by ArinzeJeffrey-droid** [comment]
> Also, I like that feature. Nice to know that if a PR has not been approved, it is not going to be merged. Very nice.

Exactly!

**Comment by Mayor-Rhymes** [comment]
I have also locally fetched and merged. Is it okay to delete the calculator branch? Want to start with calculator-logic branch.

**Comment by ArinzeJeffrey-droid** [comment]
> I have also locally fetched and merged. Is it okay to delete the calculator branch? Want to start with calculator-logic branch.

You can delete the branch.

**Comment by ArinzeJeffrey-droid** [comment]
@Mayor-Rhymes I'll be going for a lunch break now so I might not be fast in responding if that's okay?

**Comment by Mayor-Rhymes** [comment]
@ArinzeJeffrey-droid, not a problem at all. Thank you so much.

**Pull request merged**
